# Netlify configuration for React/Vite SPA
[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite outputs to 'dist' by default)
  publish = "dist"

# Redirect rules are handled by the _redirects file in public/
# But we can add additional configuration here if needed

[[headers]]
  # Cache static assets
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  # Security headers
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

